### ISSUE TITLE
Problem getting all allergens (and other taxonomies)

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/openfoodfacts-dart#394]
**Is your feature request related to a problem? Please describe.**
Allergens is a taxonomy without parents/children.
Therefore there's no notion of "root allergens" from where we could parse the tree - cf. `TaxonomyCategoryQueryConfiguration.roots`.
Therefore we cannot list all allergens, unless we already know their tags, the current configuration system being either getting the roots, or specifying the desired tags.
It's problematic if we want to say: "this is a product, those are its allergens, please add some allergens from the main list of allergens if relevant".

**Describe the solution you'd like**
An equivalent of the `roots` constructor for `TaxonomyAllergenQueryConfiguration`.

**Describe alternatives you've considered**
I've tried https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=allergens&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name, but the result was empty.

**Additional context**
I've run the same ["root query"](https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=allergens&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name) for different taxonomies - some were populated, some were empty
* Empty roots
  * TagType.STATES: 'states'
  * TagType.COUNTRIES: 'countries'
  * TagType.TRACES: 'traces'
  * TagType.ALLERGENS: 'allergens'
  * TagType.EMB_CODES: 'emb_codes'
* Populated roots
  * TagType.LABELS: 'labels'
  * TagType.CATEGORIES: 'categories'
  * TagType.INGREDIENTS: 'ingredients'
  * TagType.ADDITIVES: 'additives'
  * TagType.PACKAGING: 'packaging'
  * TagType.LANGUAGES: 'languages'

**Comment by stephanegigandet** [comment]
Thanks for the report, I'm looking into it.

**Comment by stephanegigandet** [comment]
Fixed for states, countries, allergens, traces. e.g. https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=allergens&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name

The taxonomies needed to be rebuilt.

There's no taxonomy for emb_codes

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet! Still not working for countries:
* OK for [TagType.STATES: 'states'](https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=states&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name)
* OK for [TagType.TRACES: 'traces'](https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=traces&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name)
* OK for [TagType.ALLERGENS: 'allergens'](https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=allergens&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name)
* But KO for [TagType.COUNTRIES: 'countries'](https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=countries&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name)

**Comment by stephanegigandet** [comment]
ah right, we have an issue for countries, the  taxonomy is not rebuilding, looking at it

**Comment by stephanegigandet** [comment]
should be fixed by https://github.com/openfoodfacts/openfoodfacts-server/pull/6442

**Comment by monsieurtanuki** [comment]
Thank you @stephanegigandet: here we'll just have to uncomment the test as soon as the server fix is merged.

**Comment by monsieurtanuki** [comment]
Fixed by #396.
Still waiting for https://github.com/openfoodfacts/openfoodfacts-server/pull/6442, to be completely fixed (for "all countries").
